# Generated by Django 3.0.1 on 2020-01-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200108_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='volume',
            new_name='Search',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
