# Generated by Django 3.0.1 on 2020-01-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200109_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
    ]
